[project]
name = "llm-tools"
version = "0.1.0"
description = ""
authors = [
    {name = "niwang"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "evalscope[perf] (>=0.13.2,<0.14.0)",
    "uvicorn (>=0.34.0,<0.35.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"