[project]
name = "llm-tools"
version = "0.1.0"
description = ""
authors = [
    {name = "niwang"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "sglang>=0.1.0",
    "pydantic (>=2.11.1,<3.0.0)",
    "psutil (>=7.0.0,<8.0.0)",
    "setuptools (>=78.1.0,<79.0.0)",
    "compressed-tensors (>=0.9.2,<0.10.0)",
    "datasets (>=3.0.0,<=3.2.0)",
    "decord (>=0.6.0,<0.7.0)",
    "fastapi (>=0.115.12,<0.116.0)",
    "hf-transfer (>=0.1.9,<0.2.0)",
    "huggingface-hub (>=0.30.1,<0.31.0)",
    "interegular (>=0.3.3,<0.4.0)",
    "llguidance (>=0.6.15)",
    "modelscope (>=1.24.1,<2.0.0)",
    "ninja (>=1.11.1.4,<2.0.0.0)",
    "orjson (>=3.10.16,<4.0.0)",
    "packaging (>=24.2,<25.0)",
    "pillow (>=11.2.0,<12.0.0)",
    "prometheus-client (>=0.20.0)",
    "pynvml (>=12.0.0,<13.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "pyzmq (>=25.1.2)",
    "soundfile (==0.13.1)",
    "torchao (>=0.7.0)",
    "transformers (==4.50.0)",
    "uvicorn (>=0.34.0,<0.35.0)",
    "uvloop (>=0.21.0,<0.22.0)",
    "compressed-tensors (>=0.9.2,<0.10.0)",
    "xgrammar (==0.1.17)",
    "httpx (>=0.28.1,<0.29.0)",
    "openai (>=1.70.0,<2.0.0)",
    "sgl-kernel (>=0.0.6,<0.0.7)",
    "partial-json-parser (>=0.2.1.1.post5,<0.3.0.0)",
    "flashinfer-python (<=0.2.3)",
    "nvitop (>=1.4.2,<2.0.0)",
    "einops (>=0.8.1,<0.9.0)"
]

[tool.poetry.dependencies]
python = ">=3.10,<4"
xgrammar = ">=0.1.17,<0.2.0"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
priority = "primary"
